username = input("Введите ваше имя: ")
title = input("Введите название заметки: ")
content = input("Введите содержание заметки: ")
created_date = input("Введите дату создания: ")
issue_date = input("Введите дату выполнения: ")

print("Создано:",username)
print("Название:",title)
print("Содержание:",content)
print("Дата создания:",created_date)
print("Дата выполнения:",issue_date)